//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Monocle.Resource {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResourceChina {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceChina() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Monocle.Resource.ResourceChina", typeof(ResourceChina).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Bitmap Initial {
            get {
                object obj = ResourceManager.GetObject("Initial", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Bitmap password {
            get {
                object obj = ResourceManager.GetObject("password", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 B 的本地化字符串。
        /// </summary>
        public static string StringBGain {
            get {
                return ResourceManager.GetString("StringBGain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 计算颜色失败 的本地化字符串。
        /// </summary>
        public static string StringCalculateColorFail {
            get {
                return ResourceManager.GetString("StringCalculateColorFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Duv 的本地化字符串。
        /// </summary>
        public static string StringCameraD {
            get {
                return ResourceManager.GetString("StringCameraD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 U值 的本地化字符串。
        /// </summary>
        public static string StringCameraU {
            get {
                return ResourceManager.GetString("StringCameraU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 V值 的本地化字符串。
        /// </summary>
        public static string StringCameraV {
            get {
                return ResourceManager.GetString("StringCameraV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 压力与颜色对比 的本地化字符串。
        /// </summary>
        public static string StringChartTitle {
            get {
                return ResourceManager.GetString("StringChartTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 G 的本地化字符串。
        /// </summary>
        public static string StringGGain {
            get {
                return ResourceManager.GetString("StringGGain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 编号 的本地化字符串。
        /// </summary>
        public static string StringListNum {
            get {
                return ResourceManager.GetString("StringListNum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 没有相机 的本地化字符串。
        /// </summary>
        public static string StringNoCamera {
            get {
                return ResourceManager.GetString("StringNoCamera", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 优先级不够 的本地化字符串。
        /// </summary>
        public static string StringNoEnoughPrivleges {
            get {
                return ResourceManager.GetString("StringNoEnoughPrivleges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 没有图像数据 的本地化字符串。
        /// </summary>
        public static string StringNoImageData {
            get {
                return ResourceManager.GetString("StringNoImageData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 提取配置文件失败 的本地化字符串。
        /// </summary>
        public static string StringoadConfigFileFail {
            get {
                return ResourceManager.GetString("StringoadConfigFileFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 打开相机失败 的本地化字符串。
        /// </summary>
        public static string StringOpenCameraFail {
            get {
                return ResourceManager.GetString("StringOpenCameraFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 其他错误 的本地化字符串。
        /// </summary>
        public static string StringOtherError {
            get {
                return ResourceManager.GetString("StringOtherError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 密码不正确 的本地化字符串。
        /// </summary>
        public static string StringPasswordWarning {
            get {
                return ResourceManager.GetString("StringPasswordWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 气压值 的本地化字符串。
        /// </summary>
        public static string StringPreasureValue {
            get {
                return ResourceManager.GetString("StringPreasureValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 读取Bitmap失败 的本地化字符串。
        /// </summary>
        public static string StringReadBitmapFail {
            get {
                return ResourceManager.GetString("StringReadBitmapFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 R 的本地化字符串。
        /// </summary>
        public static string StringRGain {
            get {
                return ResourceManager.GetString("StringRGain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 保存debug文件失败 的本地化字符串。
        /// </summary>
        public static string StringSaveDebugFileFail {
            get {
                return ResourceManager.GetString("StringSaveDebugFileFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 博杰 的本地化字符串。
        /// </summary>
        public static string StringTitle {
            get {
                return ResourceManager.GetString("StringTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请输入启动必须参数 的本地化字符串。
        /// </summary>
        public static string StringWarning {
            get {
                return ResourceManager.GetString("StringWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 X坐标 的本地化字符串。
        /// </summary>
        public static string StringXCorrdinate {
            get {
                return ResourceManager.GetString("StringXCorrdinate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Y坐标 的本地化字符串。
        /// </summary>
        public static string StringYCorrdiante {
            get {
                return ResourceManager.GetString("StringYCorrdiante", resourceCulture);
            }
        }
    }
}
